### ISSUE TITLE
Riorganizzazione contenuti Norme di Progetto

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#10]
Sarebbero da rivedere le parti di "Comunicazione", "Versionamento" che si sormontano un po'.

**Comment by bliberi** [comment]
Sto guardando. Alla fine le parti che si sormontano sarebbero:
a) COMUNICAZIONE
nel paragrafo 2.2.1 : 

_> Per le comunicazioni interne tra i membri del gruppo Visions Team si `e scelto di utilizzare Slack. E` stato valutato l’utilizzo di Rocket.Chat e TelegramG, il quali hanno tra i loro pregi il fatto di essere open source. Vista l’esperienza di alcuni membri del gruppo che gi`a utilizzavano Slack per altre esigenze e l’ampio numero di bot disponibili ed integrabili in esso, alla fine le alternative sono state scartate.
> Slack mette a disposizione una potente funzione di ricerca interna che permette di tenere traccia fino a 10.000 messaggi, nella versione gratuita._

che va in conflitto con il paragrafo Comunicazioni nella sezione 4.3.1.
credo che la cosa migliore sia togliere la parte dal 2.2.1 e integrarla eventualmente nel 4.3.1, mi sembra che le discussioni tecniche su Slack possano essere rimandate ai processi organizzativi.

b) VERSIONAMENTO - non ho trovato nulla di tragico. Le due parti non mi sembrano ripetitive.

Per il resto mi sembra tutto più che a posto. Modifico quel che ho detto qui sopra, in caso torniamo indietro...
