### ISSUE TITLE
Note a fondo pagina sballate

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#100]
Partono dalla 2 (cioè la 1 non esiste), e saltano la 4 (anche essa inesistente).

**Comment by Rayrven** [comment]
Ho corretto la numerazione nelle ST, prima di chiudere bisognerebbe dare un'occhiata rapida che il package caption non introduca errori in altre caption nei documenti.

**Comment by fedsib** [comment]
4f0f982 corrette footnotes in ST @Rayrven

**Comment by fedsib** [comment]
Correlata ad issue #98
