### ISSUE TITLE
Rivedere UC2, UC3 e UC4 in AdR

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#108]
* UC2: ereditarietà -> sotto-caso d'uso + rivedere scenari alternativi(scontati)
* UC3: rivedere relazioni fra casi d'uso
* UC4: rivedere per evitare similitudini con diagrammi di attività

**Comment by pbroglio** [comment]
Rimossi scenari alternativi tranne UC2.2.4 che presenta un problema su PragmaDB

**Comment by Rayrven** [comment]
Ho riaggiunto gli attori sull'UC2.2.4 e tolto lo scenario alternativo.
Però sembra saltato completamento l'inserimento di nuovi attori negli UC tramite l'interfaccia di PragmaDB, è da fare a mano sul db.
