### ISSUE TITLE
Norme di Progetto da aggiornare

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#11]
La parte di ticketing era stata pensata per gitlab. Va rivista in quanto credo che su github non ci siano priorità per le issue.

**Comment by fedsib** [comment]
In alternativa potremmo sistemare le label qui su github per fare combaciare un po' le cose.

**Comment by pbroglio** [comment]
Provate a guardare adesso, ho rimosso solo la parte di weight, il resto sembra ok
