### ISSUE TITLE
Paragrafo 6.4 di PdP: da correggere

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#110]
* La tabella 20 usa impropriamente il termine di "consuntivo" poiché al suo interno contiene anche dati relativi a stime del preventivo
* Inserire discussione che spieghi ragioni strategiche delle modifiche

**Comment by Rayrven** [comment]
Va aggiunta una specie di piccolo riassunto che spieghi il valore del preventivo a finire e cosa si intende fare per la variazione rispetto al preventivo base. Per esempio se si è risparmiato dove andranno usati o se si è oltre il limite dove/come si recupera. 
Questo però è da fare a fine periodo.

**Comment by Rayrven** [comment]
Aggiunta una piccola conclusione al preventivo a finire in b1a39c6
