### ISSUE TITLE
Riorganizzare contenuto in PdQ

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#112]
* Obiettivi di qualità presenti in 2.1 vanno specificati in modo quantitativo
* Aggiungere alla tabella delle metriche potrebbe essere una soluzione
* I contenuti di 2.3 attengono al PdP mentre 2.4 e 2.5 sono poco significativi
* In appendice B sono presenti contenuti troppo distanti da paragrafo 2
* In appendice D vanno inseriti gli esiti delle verifiche

**Comment by fedsib** [comment]
Mancano gli esiti delle verifiche, per il resto tutto ok
#139
