### ISSUE TITLE
ST: paragrafo 2 da sistemare

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#113]
Riportare pro e contro delle tecnologie utilizzate e il perché sono utili per il progetto

**Comment by czanacch** [comment]
Faccio in giornata

**Comment by czanacch** [comment]
Aggiunti i PRO e i CONTRO per Java, XML e Android ma non per FA-TTS, per quello aspetterò altre notizie..

**Comment by pbroglio** [comment]
Completo la parte di FA-TTS

**Comment by Rayrven** [comment]
Aggiunto Pro e Contro di FATTS 7b856a2
