### ISSUE TITLE
ST: Descrivere funzionalmente le componenti logiche 

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#114]

**Comment by fedsib** [comment]
PragmaDB lo fa già. Probabilmente è stato un errore rimuovere le descrizioni anche se ripetitive.

**Comment by bliberi** [comment]
Secondo me è assurdo che voglia la stessa descrizione ripetuta più volte nello stesso documento, mi sembra molto più probabile che voglia che venga descritto perché esiste la relazione

**Comment by pbroglio** [comment]
È come dice @bliberi secondo me
