### ISSUE TITLE
ST: correggere figure 1 3 9

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#116]
* fig 1: eliminare dipendenze circolari
* fig 3: rivedere relazione Bookmark-Document
* fig 9: chiarire/modificare relazioni tra fragments e activities

**Comment by pbroglio** [comment]
* Descrivere in maggior dettaglio relazioni fragments/activities

**Comment by fedsib** [comment]
La doppia relazione usata tra fragments/activities nel diagramma UML è errata e va cambiata

**Comment by fedsib** [comment]
Come facciamo ad eliminare la doppia relazione tra View e Presenter se è prevista dal pattern?

**Comment by fedsib** [comment]
fig. 3 Ad alto livello va verificata ma dovrebbe essere ok per il dettaglio non so.

**Comment by fedsib** [comment]
Figura 1 presenta ancora la dipendenza circolare.
