### ISSUE TITLE
ST: implementare figura 13 e descrizione relativa

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#118]
* Scenario di assenza di risposta del server TTS esterno
* Valore aggiunto del tracciamento di macro componenti?

**Comment by czanacch** [comment]
_Figura 13: quale lo scenario
che descrive l’assenza di risposta da parte del server TTS esterno? Avete
previsto un time-out? Quale il valore aggiunto di aver fornito un tracciamento
per le macro componenti “eBread”, “Presenter”, ...?_ 

Sistemo io con un po' di descrizione in più presa dall'incontro avuto con Paci.. non avevamo previsto timeout mi pare. Riguardo la seconda frase mi sfugge un po' il suo senso

**Comment by fedsib** [comment]
Forse tracciare i package più grandi non ha senso perché matchano con tutto? Come non possiamo evitare di tracciarli da pragma visto che altrimenti non comparirebbero più nei file esportati della ST (e della DdP)

**Comment by fedsib** [comment]
Il tracciamento va o sistemato a mano ad ogni esportazione o va cambiato direttamente l'export di Pragma. Spero non sia una rogna come al solito.

**Comment by fedsib** [comment]
Tracciamento sistemato in sistemati errori nelle tabelle 287affc @bliberi Va rivisto in seguito al cambio dei nomi dei package.

**Comment by fedsib** [comment]
Issue collegata a #134

**Comment by czanacch** [comment]
Inserito il diagramma corretto col caso della non-risposta di TTS

**Comment by Rayrven** [comment]
Corretto un attimo e ri esportato.
