### ISSUE TITLE
ST: diagramma ManagerPackage da modificare

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#119]
* In ```DocumentManager``` inserire un parametro per metodo delete di tipo intero contenente indice elemento da eliminare
* In ```XMLDocumentManager``` inserire un parametro nel metodo delete di tipo Document
* Commentare le classi

**Comment by pbroglio** [comment]
Diagrammi modificati, attendere produzione documento

**Comment by fedsib** [comment]
Ho modificato anche io per eliminare la dipendenza singolare del singleton, va verificato.

**Comment by fedsib** [comment]
Occorre rivederlo dopo l'adozione di Dagger, il diagramma non è più attuale.
