### ISSUE TITLE
Registro delle modifiche

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#120]
"La localizzazione delle modifiche effettuate aumenterà specificandola in modo numerico e non narrativo; occorrerà anche migliorarne la tracciabilità rispetto alle decisioni o esigenze di modifica."

Potremmo associarci un codice per tracciare le modifiche e indicare il numero di pagina delle pagine modificate. Dovrebbe bastare a risolvere.

**Comment by Rayrven** [comment]
Sono da riverificare.
