### ISSUE TITLE
ST: Creazione dei nuovi diagrammi delle attività (algoritmica del sistema)

### ISSUE THREAD

**Issue by czanacch** [Visions-Team/eBread-docs#123]
I diagrammi delle attività della STv1 vanno sostituiti con diagrammi più specifici che illustrano il funzionamento del sistema dal punto di vista algoritmico.

**Comment by czanacch** [comment]
Cerco di fare tutti i diagrammi delle attività nuovi entro domenica 2 aprile

**Comment by czanacch** [comment]
Vengono un po' grandi... mancano i diagrammi di ShowDocumentActivity e SettingListActivity.
Probabilmente saranno spezzati in sotto-attività.
Questo per esempio è il diagramma per DocumentListActivity:
![documentlistactivity](https://cloud.githubusercontent.com/assets/24655055/24617007/0574f538-1893-11e7-9bef-25eb01e8802f.png)

**Comment by czanacch** [comment]
Inseriti e riadattati tutti i diagrammi, ad eccezione di ShowDocumentActivity (di conseguenza ShowDocumentFragment) per cui ho un po' di difficoltà... comincio ad aggiornare il documento LaTex con le descrizioni per ogni diagramma

**Comment by czanacch** [comment]
Correggerò alcuni diagrammi, mi sono reso conto che in alcuni casi  (come quello della visualizzazione dell'anteprima del testo) serve una fork per modellare l'attività parallela

**Comment by czanacch** [comment]
Finiti i diagrammi delle attività (sono 11 in totale) e le descrizioni nel file attivita.tex
Vanno solo esportate immagini in .pdf da file .astah (o in pdf_tex??? xD ) collegati i giusti path e ridimensionate un po' le immagini all'interno del documento (solito problema delle spaziature).

**Comment by fedsib** [comment]
Ok, domani provo a darci un'occhiata, son tutti su drive?

**Comment by czanacch** [comment]
Tutti i diagrammi sono su Drive, vanno convertiti in pdf e aggiornati i path nel file .tex

**Comment by czanacch** [comment]
Caricati in bin/img/st/attivita/pdf_tex tutti gli 11 diagrammi nuovi in formato .pdf, restano da cambiare i path del file attivita.tex e testare come appaiono le immagini nel documento

**Comment by fedsib** [comment]
OK domani li aggiorno

**Comment by fedsib** [comment]
Inseriti diagrammi delle attività e verificato il testo, se qualcun altro può darci un'occhiata si può chiudere
