### ISSUE TITLE
AR: Inserimento sezione "Diagrammi delle attività"

### ISSUE THREAD

**Issue by czanacch** [Visions-Team/eBread-docs#124]
I diagrammi delle attività della STv1 andranno spostati nel documento ARv3 in quanto illustrano il procedimento algoritmico che l'utente dovrebbe compiere per utilizzare l'applicazione.

**Comment by fedsib** [comment]
cb3b538 by @czanacch

**Comment by fedsib** [comment]
Occorre rivedere la spaziatura
