### ISSUE TITLE
DdP: Diagrammi di Sequenza

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#126]
Occorre creare i diagrammi di sequenza e le relative descrizioni.

**Comment by czanacch** [comment]
Dando un'occhiata a vari documenti un diagramma di sequenza è abbinato a una "Azione", dunque non un package o altre strutture particolari. Per farli dobbiamo aspettare che sia tutto pronto perchè ci servono i nomi dei metodi in una visione generale di tutta l'applicazione

**Comment by czanacch** [comment]
Caricati in una cartella bin/res/diagrammi_astah i file .astah per i diagrammi di sequenza (5 in totale) dello ShowDocumentActivity. Non posso assicurare la loro correttezza in quanto ci sono stati spiegati molto approssimativamente

**Comment by Rayrven** [comment]
Ho caricato due diagrammi per ShowDocumentFragment, non coprono tutto ci sarebbe veramente troppo... E ho aggiunto una descrizione per la DP.

**Comment by czanacch** [comment]
Aggiornati i path che puntano ai file pdf con le immagini... adesso manca solo da controllare come le immagini vengano visualizzate nel documento e da cambiare un titolo "Erogazione della voce" che appare due volte (la prima accompagnata da subsubsection)

**Comment by Rayrven** [comment]
Sono stati rivisti e corretti.
