### ISSUE TITLE
Aggiunta termini in glossario

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#132]
Issue per elencare i termini da aggiungere al glossario v3

**Comment by fedsib** [comment]
Volley

**Comment by fedsib** [comment]
lipsync?

**Comment by fedsib** [comment]
Failure Avoidance , Breakdown Avoidance , Average Module Syze

**Comment by fedsib** [comment]
Analisi statica, analisi dinamica

**Comment by Rayrven** [comment]
Firebase Test Lab

**Comment by pbroglio** [comment]
* RoboTest
* API(da controllare, immagino sia già presente)

**Comment by Rayrven** [comment]
Aggiunte tutte le parole fino ad ora scritte qua a56400a

**Comment by fedsib** [comment]
Mah... Abbiamo veramente ancora roba da aggiungerci? Io la chiuderei

**Comment by Rayrven** [comment]
Fino a che i documenti non sono tutti completi la possibilità c'è sempre
