### ISSUE TITLE
Creazione del manuale utente

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#133]
Il manuale utente è uno dei documenti richiesti per la RQ. 
http://www.math.unipd.it/~tullio/IS-1/2016/Dispense/L09.pdf

**Comment by fedsib** [comment]
Va incluso nell'applicazione. Il PDF non è fruibile potremmo usare le github pages.

**Comment by ebortolin** [comment]
L'ho aggiunto al posto del documento di prova.

**Comment by fedsib** [comment]
Completata sezione 4 "Segnalazione bug"

**Comment by fedsib** [comment]
Completata sezione 0 "Introduzione" e 1 "Guida all'installazione" 
https://fedsib.gitbooks.io/ebread-user-manual/content/

**Comment by fedsib** [comment]
Completata sezione 5 glossario.

**Comment by fedsib** [comment]
Ora manca solo la parte sugli errori e poi la verifica

**Comment by fedsib** [comment]
Aggiungiamo anche qui una riga sulla licenza?
