### ISSUE TITLE
DdP: Crezione diagrammi delle classi

### ISSUE THREAD

**Issue by czanacch** [Visions-Team/eBread-docs#135]
Ogni classe (con tutti i suoi campi dati e metodi) va formalizzata con un diagramma UML della classe, ovvero il rettangolo specifico della classe.

**Comment by czanacch** [comment]
I diagrammi ci sono tutti tranne quello di ShowDocumentFragment e qualche classe/interfaccia interna. Quando si esporterà da PragmaDB darò una ripassata generale.

**Comment by fedsib** [comment]
Aspettiamo quindi l'export da Pragma

**Comment by Rayrven** [comment]
Ho ricontrollato i diagrammi ed esportati in svg e pdf... dovrebbero essere tutti a posto con il tracciamento su Pragma. Serve l'export che non va
