### ISSUE TITLE
ST: Descrizioni diagrammi attività 

### ISSUE THREAD

**Issue by bliberi** [Visions-Team/eBread-docs#145]
Sono troppo dettagliati. Se c'è tempo, da rivedere.

**Comment by czanacch** [comment]
Teoricamente l'algoritmica del sistema dovrebbe essere più dettagliata rispetto a come li avevamo fatti nella RP (per questo quelli sono stati spostati nell'AR).

**Comment by bliberi** [comment]
Sì, ma si parla di RadioButton e cose varie che sono troppo specifiche. Comunque ho fatto
