### ISSUE TITLE
DdP: Rivedere campi statici

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#156]
Fig. 13: un attributo della classe ha il nome in maiuscolo ma non è statico. 
I campi dati statici devono essere sottolineati

**Comment by czanacch** [comment]
Il campo dati
`public static final int PICK_DOCUMENT_CODE = 1` è effettivamente statico e l'errore sta nel diagramma. Rimanderei le correzioni di tutti i diagrammi e di Pragma quando il codice sarà definitivo in modo da non modificare continuamente.
