### ISSUE TITLE
DdP: Segnali Figura 40 e 41

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#157]
Fig. 40: Rivedere l’invio dei segnali fra le componenti, perché sono stati utilizzati dei
tipi di segnali di “ritorno”, invece che di “invio“.

**Comment by czanacch** [comment]
Anche nella 41; faccio io

**Comment by czanacch** [comment]
Questo lo chiedo a Cardin martedì... nelle sue slide ci sono segnali di tipo <<create>> utilizzati come segnali di invio.. non capisco bene dove sta la sua contestazione...
