### ISSUE TITLE
ST:  Approfondire descrizione architetturale ad alto livello

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#160]
Continua a mancare una chiara descrizione architetturale ad alto livello del prodotto per descrivere, tra
l’altro, come interagiscono le componenti, in che modo i framework e librerie utilizzare si integrano con le componenti logiche dell’architettura.

**Comment by pbroglio** [comment]
Ho provato ad aggiungere la descrizione, ma è abbastanza oscura come richiesta. Provate a darci un'occhiata. Link al commit -> 0b4ea9c

**Comment by bliberi** [comment]
A me sembra che possa andare bene, ma per l'appunto non si capisce bene cosa sia richiesto; soprattutto la parte del framework... che voglia che si parli tipo del fatto che alcune classi ereditano/implementano classi già presenti nella libreria android e perché?
