### ISSUE TITLE
ST: Diagrammi delle classi dei Design Pattern

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#161]
Come segnalato in sede di RP, è necessario che la contestualizzazione dei design pattern utilizzati si avvalga di diagrammi delle classi dedicati.

**Comment by bliberi** [comment]
Mancherebbe ancora il diagramma per dependency injection ma non saprei bene come farlo, con Dagger di mezzo

**Comment by fedsib** [comment]
Boh, io non lo rappresenterei e chiuderei
