### ISSUE TITLE
ST: Rivedere tracciamento

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#162]
Il tracciamento dei requisiti deve essere con le componenti logiche del sistema, che non possono essere altro che le classi individuate nel documento ST.

**Comment by fedsib** [comment]
Non è ben chiaro cosa intenda.

**Comment by czanacch** [comment]
Va fatto tracciamento Classi-Requisiti anche nella ST.

**Comment by bliberi** [comment]
Ho sostituito il tracciamento Componenti/Requisiti con il tracciamento Classi/Requisiti uguale a quello della DdP, commit [f05d67f](https://github.com/Visions-Team/eBread-docs/commit/f05d67f0843fd52ba15b8652eb3577dea8ad5898)
