### ISSUE TITLE
Aggiornamento PragmaDB con nuove classi, metodi e campi dati

### ISSUE THREAD

**Issue by czanacch** [Visions-Team/eBread-docs#168]

**Comment by czanacch** [comment]
Con l'aggiunta di classi come HtmlDocument e EPubDocument, sottotipi di Document, c'è da aggiornare i diagrammi delle classi della ST

**Comment by bliberi** [comment]
HtmlDocument e EpubDocument sono state aggiunte su ST, DdP e Pragma con relativi diagrammi. Modificato anche il tracciamento.
