### ISSUE TITLE
DdP: Rivedere tutti i diagrammi delle classi

### ISSUE THREAD

**Issue by czanacch** [Visions-Team/eBread-docs#169]
Quando il codice sarà finito ogni diagramma .astah delle singole classi sarà rivisto, e infine ri-esportato in .pdf per il documento LaTex

**Comment by czanacch** [comment]
Aggiunta la cartella con i file .astah in bin/res/diagrammi_astah/ RA - Diagrammi delle classi finali (DdP), a breve converto in .pdf per la solita cartella bin/img/dp/diagrammi_classi/model/documents/pdf

**Comment by Rayrven** [comment]
Ricontrollati i diagrammi correggendo gli errori trovati.
