### ISSUE TITLE
Creazione del manuale dello sviluppatore

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#171]

**Comment by fedsib** [comment]
E' a posto? Si può passare per le verifiche finali?

**Comment by bliberi** [comment]
Io ho letto tutto quanto e corretto qualcosa qua e là ma mi pare ottimo

**Comment by fedsib** [comment]
Sarebbe da aggiungere una parte sulla licenza di eBread (ma occorre decidere che licenza usare, probabilmente GPL vedendo FATTS/MaryTTS) e decidere sul glossario

**Comment by pbroglio** [comment]
Io direi la [GNU GPL-3](https://choosealicense.com/licenses/gpl-3.0/)
