### ISSUE TITLE
Creazione diagrammi UC

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#19]

**Comment by czanacch** [comment]
Se l'attuale UC7 (dal nome "Utilizzo della funzione TTS") viene impostato come terzo figlio di UC6 (dal nome "Navigazione nel documento") ovviamente verrà fatto un unico diagramma UC per UC6; in caso contrario verrebbero fatti tre diagrammi per i tre figli di UC6

**Comment by pbroglio** [comment]
Meno diagrammi abbiamo meglio è

**Comment by czanacch** [comment]
Allora io parto con il diagramma di UC6

**Comment by pbroglio** [comment]
Quello generale posso farlo io?

**Comment by czanacch** [comment]
Certo

**Comment by pbroglio** [comment]
Perché su Pragma ci sono solo 6 UC? @czanacch Stai aspettando quelli di @Ciaaa95 ?

**Comment by czanacch** [comment]
![image](https://cloud.githubusercontent.com/assets/24655055/21614612/6ef0ac0a-d1da-11e6-85ce-61ade13e9076.png)

Questa è una piccola bozza.
@pbroglio ho ridotto 3 UC a figli dello UC 6 in quanto era logicamente più corretto. La numerazione di Pragma è tutta automatica.

**Comment by pbroglio** [comment]
Ottimo

**Comment by pbroglio** [comment]
![usecase ebread](https://cloud.githubusercontent.com/assets/11090618/21640504/312190c8-d276-11e6-9cf7-5c00ee9b20e5.png)

**Comment by pbroglio** [comment]
Adesso bisognerebbe fare i diagrammi dei casi d'uso più importanti

**Comment by pbroglio** [comment]
![uc3](https://cloud.githubusercontent.com/assets/11090618/21647608/4d156406-d29b-11e6-9b2c-d0729a25cc08.png)

**Comment by pbroglio** [comment]
![uc10_ebread](https://cloud.githubusercontent.com/assets/11090618/21648273/bf470bb8-d29d-11e6-8d5e-5b1729d3b83f.png)

**Comment by Ciaaa95** [comment]
Bozza UC2

![uc2](https://cloud.githubusercontent.com/assets/22904376/21677212/6f50a348-d339-11e6-80fa-3011194c3fac.png)

**Comment by czanacch** [comment]
![image](https://cloud.githubusercontent.com/assets/24655055/21679959/101ab252-d347-11e6-8c75-c2c1a1b758fd.png)

Questa è una bozza per UC6 ... come vedete ho editato in questo modo l'angolo in alto a sinistra. Secondo me è meglio che lo facciate anche voi editando i vostri in modo che le immagini stesse siano più specifiche.. ditemi voi

**Comment by czanacch** [comment]
Scrivete qui se pensate che abbia sbagliato qualcosa.. per esempio UC6.3.1 e UC6.3.2 non sono sicuro al 100% che siano corretti logicamente con la sintassi UML...
