### ISSUE TITLE
Approvazione Piano di Qualifica

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#22]

**Comment by bliberi** [comment]
Se qualcuno ha verificato la sezione degli standard di qualità, la verifica è completata.

**Comment by fedsib** [comment]
Verificato con Aspell, tutto ok. Meglio se qualcun altro da un'occhiata alla sezione standard (io l'ho guardata durante l'hangout e mi sembrava ok)

**Comment by Rayrven** [comment]
Ho dato un'occhiata, sembra tutto a posto e corretto

**Comment by pbroglio** [comment]
Passo all'approvazione allora
