### ISSUE TITLE
Completare log delle modifiche di Piano di Qualifica

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#25]

**Comment by pbroglio** [comment]
Approvazione avvenuta

**Comment by Rayrven** [comment]
Ho fatto il push con le modifiche, se qualcuno controlla poi è a posto

**Comment by pbroglio** [comment]
Faccio io

**Comment by pbroglio** [comment]
Fermo alla versione 0.6.0 perché manca la questione della verifica?

**Comment by Rayrven** [comment]
Sì, manca l'esito della verifica ed il suo controllo prima che sia considerato pronto alla consegna

**Comment by pbroglio** [comment]
Va bene allora
