### ISSUE TITLE
Verifica Analisi dei Requisiti

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#28]

**Comment by czanacch** [comment]
**Grammatica da correggere:**

INTRODUZIONE
1.3 Glossario
- "Per evitare questa ambiguità è stato creato un documento di Glossario" dovrebbe diventare "è stato creato un documento DI NOME Glossario"
1.4 Riferimenti
- nell'elenco puntato la voce "Dall’idea al codice con UML 2 - L. Baresi, L. Lavazza, M.
Pianciamore - Prima edizione (2006):. "   va corretta   ---> ci sono due punti di troppo dopo 2006.

DESCRIZIONE GENERALE
2.1 Prospettive del prodotto
- è "un ebook reader" e non "un eboor reader"
2.2 Funzioni di prodotto
-  "L’utente potrà configurare vari parametri, in qualsiasi momento dell’utilizzo dell’applicazione, particolare attenzione andrà posta alla configurazione iniziale, che avverrà al primo avvio
del software." va un po' corretta grammaticalmente.
- Nell'elenco va messo un punto alla fine e manca un punto e virgola in una voce

**Errori logici**
Nella descrizione di "Scenario principale" viene specificato che questo punto è una lista numerata- Ciò non è sempre vero (ci sono UC scritti in modo tale che "Scenario principale" non sia una lista numerata.

**ATTENZIONE AI DIAGRAMMI UC**: 
Gli attori che vengono dichiarati dovrebbero essere collegati con i giusti casi d'uso.
Questi sono i casi d'uso la cui descrizione testuale/grafica presenta inconsistenze:
- UC2: 2.2.1, 2.2.2.1
- UC3: 3.1, 3.3
- UC6: 6 stesso, 6.3, 6.3.1 e 6.3.2
- UC8: 8.1 
- UC9: 9 stesso,
- UC10: 10 stesso, tutti gli altri hanno in comune sia l'Utente che TTS, per cui sarebbe bene correggere il diagramma.

L'attore che rappresenta la sintesi vocale andrebbe chiamato "FA-TTS" anche sui diagrammi per rispecchiare la descrizione.

**Comment by czanacch** [comment]
**Requisiti da correggere**
Descrizione da correggere
_RFO1.2.1:_ sostituzione "”eBread” mostra pagina" -> "”eBread” mostra la pagina"
_RFO1.2.2:_ sostituzione "”eBread” mostra lista dei documenti" -> "”eBread” mostra la lista dei documenti"

_RFF8:_ sostituire "libreria" con "lista dei documenti"

_RFO10.1.1 e RFO10.1.2:_ si deve fare chiarezza sulla modalità di scorrimento del documento, visto che qui è segnato "dall'alto verso il basso" e "dal basso verso l'alto" quando negli UC è indicato che l'utente scorre il dito da sinistra a destra e viceversa.

**Comment by czanacch** [comment]
Fatto il push con le modifiche (non quelle della descrizione dei requisiti).. adesso si tratta di modificare le immagini (principalmente cambiare il nome da "TTS-Engine" o "motore TTS" a "FA-TTS".
