### ISSUE TITLE
Approvazione PDP - Chiarimenti

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#38]
Nella tabella d'approvazione del Piano di Progetto, credo vada messa @Ciaaa95 al posto di @pbroglio

**Comment by bliberi** [comment]
Nel primo periodo i responsabili sono Lucia, Marco e Paolo, per cui non dovrebbe essere un errore

**Comment by Ciaaa95** [comment]
eh non so se debba essere approvato dal responsabile del documento o basta uno qualunque dei responsabili in quel periodo...

**Comment by bliberi** [comment]
Giusta osservazione. Ritiro quel che ho detto, mi sa che avete ragione. Siccome sto facendo delle modifiche, se dite lo cambio io

**Comment by fedsib** [comment]
Uhm forse sbaglio io, e si riferisce all'approvazione dell'organigramma di gruppo non al documento, quindi sarebbe corretto. Non so.

**Comment by bliberi** [comment]
Gli altri gruppi, tranne gli hotkeys e gli steakholders che però avevano una roba strana di un responsabile in deroga, hanno messo il responsabile del documento per l'approvazione. Credo che se mettiamo Lucia sia giusto di sicuro, mentre con Paolo potrebbe essere giusto come no

**Comment by fedsib** [comment]
Uhm si, penso sia corretto come dici @bliberi

**Comment by bliberi** [comment]
Cambio allora visto che ho delle modifiche da pushare? Poi quando torna @Rayrven ci dice le sue motivazioni e al massimo si ricambia
