### ISSUE TITLE
Aggiungere sezione di validazione nei processi di supporto in NdP

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#42]
Bisogna aggiungere la parte che riguarda la validazione dopo la verifica nelle Norme di Progetto

**Comment by pbroglio** [comment]
Ho ancora qualche dubbio sulla correttezza di ciò che ho scritto quindi credo che farò una *pull request* in modo che prima di pushare possiate darci un'occhiata anche voi

**Comment by pbroglio** [comment]
Guardare la issue#61

**Comment by fedsib** [comment]
Ok, provo a darci un'occhiata
