### ISSUE TITLE
Implementare le norme di progettazione

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#43]
* Posizionarle prima delle norme di codifica
* Aggiungere contenuto per renderle ampie almeno quanto quelle di codifica

**Comment by bliberi** [comment]
Ho caricato, fondamentalmente ho ampliato un po' la prima parte e aggiunto tutte le norme che useremo per l'UML. Ci vuole che qualcuno controlli con senno perché ho paura che in alcune parti sia troppo prolisso, o di non aver centrato esattamente l'obiettivo e quindi di dover aggiungere ancora qualcos'altro

**Comment by pbroglio** [comment]
Guardo io

**Comment by pbroglio** [comment]
Mi pare perfetto, ottimo lavoro
