### ISSUE TITLE
Aggiungere versionamento nella gestione di configurazione

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#44]

**Comment by Rayrven** [comment]
Ho modificato l'ordine ed il nome per il versionamento.
Mi son basato sull'ordine presente qui: https://en.wikipedia.org/wiki/IEEE_12207
Quindi ho spostato il versionamento prima di processo di documentazione.
Poi è stata aggiunta una subsection con gestione di configurazione e subsubsection con processo di versionamento, rendendo tutto il contenuto del versionamento dei paragraph.
Sto considerando se sia possibile aggiungere anche del contenuto aggiuntivo al versionamento ma penso sia a posto se qualcuno controlla.
