### ISSUE TITLE
Analisi dei rischi in forma tabellare

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#66]

**Comment by pbroglio** [comment]
Aggiungere l'attualizzazione dei rischi

**Comment by bliberi** [comment]
Attenzione se alla fine non lo facciamo, nel PdQ a pag. 27 c'è già scritto che lo abbiamo fatto e dobbiamo quindi eliminare la frase: "Inoltre è stato tentato un miglioramento dell'analisi dei rischi presentando una tabella riassuntiva di più rapida consultazione".

**Comment by Rayrven** [comment]
La tabella riassuntiva per l'analisi dei rischi è stata fatta, quello che manca è il suo miglioramento renendola più completa ed aggiungendo l'attualizzazione.

**Comment by pbroglio** [comment]
Ragazzi i label però vanno usati
