### ISSUE TITLE
Sistemazione norme conformandole al nuovo PDQ

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#69]
Vanno aggiunti / sistemati i dettagli delle metriche. Issue collegata alla #68

**Comment by fedsib** [comment]
Aggiunta appendice NdP sulle metriche aa4ea59

**Comment by fedsib** [comment]
Da verificare.

**Comment by pbroglio** [comment]
Verifico

**Comment by fedsib** [comment]
Ho lasciato SFIN e SFOUT (accoppiamento afferente ed efferente) nella sola appendice perché vengono citati nella formula di calcolo dell'instabilità sennò manco si sapeva cosa fossero.

**Comment by pbroglio** [comment]
Verificato, chiudo
