### ISSUE TITLE
Correzioni documenti negli altri branch con i nuovi comandi

### ISSUE THREAD

**Issue by Rayrven** [Visions-Team/eBread-docs#7]
La lista delle figure e delle immagini richiedono un comando che indica se tali liste sono necessarie.
Si necessita di aggiornare i documenti nei rispettivi branch aggiungendo:
\newcommand{\ListaTabelle}{false}
\newcommand{\ListaImmagini}{false}

ovviamente impostando true se ci fosse una tabella od una immagine da inserire nella tabella

**Comment by pbroglio** [comment]
Inserito nel Piano di Progetto

**Comment by Rayrven** [comment]
Lo Studio di Fattibilità è stato aggiornato

**Comment by pbroglio** [comment]
Inserito nelle Norme di Progetto
