### ISSUE TITLE
Stesura "Componenti e Classi" su ST

### ISSUE THREAD

**Issue by Ciaaa95** [Visions-Team/eBread-docs#71]

**Comment by bliberi** [comment]
Componenti finiti a meno di qualche correzione, tuttavia ho problemi con le immagini svg perché quando le importo nel documento sono sempre precedute da una banda bianca, uno spazio di cinque/sei righe o anche più, non riesco a capire da cosa dipenda... qualcuno ha idea di cosa sia? Il pdf dovrebbe essere tagliato giusto

**Comment by fedsib** [comment]
Ma te la sei fatta a mano? Bastava inserire i dati in pragma e credo li esportasse in automatico, ora provo a vedere cos'ha di strano il pdf

**Comment by bliberi** [comment]
Ah. Non lo sapevo. Sì, li abbiamo fatti a mano.

**Comment by fedsib** [comment]
Associata alla issue #77

**Comment by pbroglio** [comment]
@bliberi mi aggiungo a lavorare su questo ticket

**Comment by fedsib** [comment]
L'export del file ST da pragma può sostituire entrambe le sezioni classi e componenti, sembra.

**Comment by fedsib** [comment]
Per la questione delle descrizioni è un casino da sistemare su Pragma per domani. Sembra @bliberi modificherà a mano il file, altrimenti consegniamo questo.

**Comment by bliberi** [comment]
Ho già finito di modificare. Sto valutando se cambiare l'ordine dei componenti per fare in modo che prima vengano nominati i padri e poi i figli, in questo momento è tutto alla rinfusa in ordine alfabetico

**Comment by pbroglio** [comment]
@bliberi Sono d'accordo nel dare un ordine di tipo gerarchico

**Comment by pbroglio** [comment]
Ho verificato le descrizioni e sono molto buone, per me una volta sistemata la questione grafica si può chiudere il ticket

**Comment by fedsib** [comment]
+1 Per l'ordinamento gerarchico. Occorrerà verificare come viene, ma sono fiducioso.

**Comment by pbroglio** [comment]
Si può chiudere?

**Comment by fedsib** [comment]
Provo a vedere un secondo

**Comment by fedsib** [comment]
Direi di si, mi pare perfetto anche se magari prima era un po' più immediato anche se palloso.
