### ISSUE TITLE
Stesura "Mockup" su ST

### ISSUE THREAD

**Issue by Ciaaa95** [Visions-Team/eBread-docs#73]

**Comment by fedsib** [comment]
Prima bozza in 2129175

**Comment by ebortolin** [comment]
Verifico io

**Comment by fedsib** [comment]
`0a3a79b` Verifica mockup - @ebortolin

**Comment by pbroglio** [comment]
Bisogna specificare che il testo d'esempio inserito delimita l'area e non rappresenta il contenuto stesso
