### ISSUE TITLE
Stesura "Tracciamento" su ST

### ISSUE THREAD

**Issue by Ciaaa95** [Visions-Team/eBread-docs#77]

**Comment by bliberi** [comment]
Ho finito il tracciamento ma ho dei dubbi/osservazioni su alcuni requisiti:

_- RFF3 e figli: Utente generico può creare la propria voce, Utente generico deve leggere una lista di frasi, Le frasi sono generate da FA-TTS, Utente generico può registrare la propria voce, Utente generico preme un bottone per cominciare la registrazione, FA-TTS crea la voce usando la registrazione, ``eBread" chiede a Utente generico di salvare con nome la voce creata, Utente generico inserisce il nome con cui salvare la voce creata, ``eBread" inserisce voce creata tra la lista delle voci disponibili.
-RFF13 e figli:	Utente può eliminare voci dalla lista, Una voce può essere cancellata solo se è stata creata dall'utente, L'utente può selezionare più voci da eliminare contemporaneamente
- RFF14 ``eBread" restituisce un messaggio d'errore se il nome della voce creata è già presente_
Per tutti i 3 precedenti: essendo non accettati non li traccerei, altrimenti direi che la cosa migliore è tracciarli su SettingListActivity/Fattssetting

_- RFO5.1	Il documento importato deve essere supportato da ``eBread"
- RFO5.2	Il documento deve essere disponibile nella memoria del dispositivo mobile
- RFO5.2.1 Utente generico può cercare il documento nel file system del dispositivo mobile
- RFO5.3	``eBread" restituisce un messaggio d'errore se il file non è supportato_
DocumentManager ha il metodo loadDocument() che si occupa di andare a recuperare il file, creare l'oggetto Document e andare a salvare sull'xml, quindi li ho tracciati lì anche se in realtà bisognerà fare altro per accedere al filesystem... per ora va bene così? 

_- RFD7.2.2.1 Utente generico può ascoltare una frase d'esempio della voce selezionata_
L'ho tracciato su SettingDetailFragment, ma questo requisito impone delle correlazioni della classe con fa-tts o saranno delle prove audio già presenti nel cellulare (si tratta alla fine di poche voci)? in tal caso l'uri di questi file verrà salvato su fattssetting e quindi bisogna aggiungere il tracciamento del requisito anche lì?

_- RFF8 e figli: ``eBread" mostra libreria contenente i documenti._
Non l'abbiamo pensata nella progettazione, anche se in realtà penso che sarebbe sempre DocumentListActivity con una view sofisticata, perciò eventualmente vanno tracciati lì

_- RFO10.3.2 Utente generico seleziona il segnalibro su cui spostarsi_
Dopo questo requisito sarebbe il caso di metterne un altro del tipo "il documento si apre al segnalibro selezionato" da tracciare su Document e ShowDocumentFragment

_-RFF15 e figli:	Utente può usare il menù di navigazione in documenti ben formati, Utente può spostarsi tra i capitoli, ``eBread" mostra la lista dei capitoli, Utente può selezionare il capitolo su cui spostarsi, Un documento ben formato è un documento che ha un indice_
Non ci siamo assolutamente occupati di questa cosa, dove la traccio? Su Showdocumentfragment e Document e poi chi vivrà vedrà?

_- RFD16	Si dispone di un layout ottimizzato per la visualizzazione su dispositivo tablet_
un altro non accettato, non l'ho tracciato 

_- RQO1	Deve essere fornito il manuale d'uso per aiutare l'utente nell'utilizzo dell'applicazione
- RQO2	Lo sviluppo del prodotto rispetta i criteri definiti nei documenti ``Norme di Progetto v1.0.0" e ``Piano di Qualifica v1.0.0"
- RVO1	``eBread" deve funzionare su piattaforme Android con versione superiore o uguale a 4.2.1 e livello API 17_
Essendo di qualità/vincolo non li ho tracciati, l'unico di vincolo tracciato è _RVF2: "Il sistema è integrato con un Engine TTS alternativo per la riproduzione in mancanza di connessione internet"_ che ho tracciato su Synth

**Comment by fedsib** [comment]
0559600 Aggiunto tracciamento requisiti-componenti, componenti-requisiti. chiudo
