### ISSUE TITLE
Creazione del verbale esterno del 23/02

### ISSUE THREAD

**Issue by pbroglio** [Visions-Team/eBread-docs#83]
Creazione del verbale esterno completo di:
* Informazioni(Data, ora, luogo)
* Ordine del giorno
* Verbale

**Comment by fedsib** [comment]
Creato verbale VER-2017-02-23 2e86332 @pbroglio

**Comment by pbroglio** [comment]
Il PDF è apposto?

**Comment by fedsib** [comment]
Sistemato VER-2017-02-23 ora compila  @Ciaaa95 3f36c29
