### ISSUE TITLE
Verifica e Approvazione AR

### ISSUE THREAD

**Issue by Rayrven** [Visions-Team/eBread-docs#86]
Bisogna verificare rapidamente l'analisi dei requisiti ed approvarla per la consegna.

**Comment by fedsib** [comment]
Ci do una passata anche con Aspell

**Comment by czanacch** [comment]
Posso procedere all'eliminazione degli UC ormai inutili da PragmaDB

**Comment by fedsib** [comment]
Aspettiamo di sistemare gli UC su pragma #94

**Comment by fedsib** [comment]
41a4565 by @czanacch Correzione UC a mano.
