### ISSUE TITLE
Analisi di occorrenza PDP

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#87]
Dalla lista delle correzioni della RR: "Manca inoltre una analisi di occorrenza (ed eventuale mitigazione) attualizzata al periodo di rendicontazione." E' a posto?

**Comment by Ciaaa95** [comment]
Questa parte dobbiamo ancora farla se non sbaglio ... La aggiungiamo come appendice oppure nella sezione dell'analisi dei rischi sotto la tabella?

**Comment by Ciaaa95** [comment]
Commit: 957852cc412c6c8c3475b0adb52d646ffe9ede95
