### ISSUE TITLE
Correzioni a seguito della Revisione 

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#88]
Manca sottosezione

**Comment by Rayrven** [comment]
Aggiunto a fine PdQ, da verificare.

**Comment by pbroglio** [comment]
Se qualcuno carica il pdf compilato posso verificarlo visto che longtabu non funziona su OS X

**Comment by pbroglio** [comment]
La sottosezione va bene. Chiudo il ticket
