### ISSUE TITLE
Requisiti accettati sull'AR

### ISSUE THREAD

**Issue by fedsib** [Visions-Team/eBread-docs#89]
Mancano, la tabella viene generata da pragma, basta includerla.

**Comment by fedsib** [comment]
Modificherò Pragma

**Comment by Rayrven** [comment]
La tabella non viene "generata" da PragmaDB. Viene esportato un semplice Itemize con la lista dei soli requisiti accettati.
Ho modificato il testo così che venga comunque presentato come una tabella simile alle altre con tutti i requisiti non obbligatori aggiungendo se sono stati accettati o meno.
